version: "3.8"

services:
  node-server:
    build: ./node-server
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf



